### ISSUE TITLE
better widescreen support

### ISSUE THREAD

**Issue by johnnychen94** [lorenzoh/Pollen.jl#72]
This what it looks like in a 4K display; the single column version only occupies less than 1/3 of the screen makes it visually not very comfortable.

<img src="https://user-images.githubusercontent.com/8684355/168266982-886d05d0-af63-43a7-b47f-855e60afd57f.png" width=1024>

<img src="https://user-images.githubusercontent.com/8684355/168266552-641f06fe-f0fd-4747-a48d-808b7db5ee26.png" width=1024>

**Comment by lorenzoh** [comment]
What would you want it to look like?

**Comment by johnnychen94** [comment]
For the double columns case, it should expand to the entire window, I think?

**Comment by lorenzoh** [comment]
I think you should be able to set the default zoom in your browser settings to get something that will look nice on large screens

**Comment by johnnychen94** [comment]
Oooooh! I should have really tried this before opening the issue!
