### ISSUE TITLE
Popup when leaving site

### ISSUE THREAD

**Issue by KronosTheLate** [lorenzoh/Pollen.jl#77]
When trying to leave the docs for `FluxTraining`, I get the following popup each time:
![image](https://user-images.githubusercontent.com/61620837/174322275-c17034db-13bd-4903-95d6-167821cc1a58.png)

This is annoying, and I have made no changes that should be saved. 
The docs look great though ^_^

**Comment by lorenzoh** [comment]
Just pushed a fix to the frontend (https://github.com/lorenzoh/pollenjl-frontend) and triggered a rebuild of the docs, which should be live in a few minutes 👍
