### ISSUE TITLE
feature request: cell copy button for plain text

### ISSUE THREAD

**Issue by johnnychen94** [lorenzoh/Pollen.jl#80]
This is what I get on windows 10 via Ctrl-C + Ctrl-V from https://lorenzoh.github.io/Pollen.jl/dev/documents/docs/tutorials/setup.md when editing this issue directly on GitHub.
It seems that GitHub is being too smart to insert markdown URLs here.

```julia
using PkgTemplates, [Pollen](https://lorenzoh.github.io/Pollen.jl/dev/documents/docs/tutorials/setup.md?id=references/Pollen&focus=1)

template = Template(plugins=[
        [Pollen](https://lorenzoh.github.io/Pollen.jl/dev/documents/docs/tutorials/setup.md?id=references/Pollen&focus=1).[PollenPlugin](https://lorenzoh.github.io/Pollen.jl/dev/documents/docs/tutorials/setup.md?id=references/Pollen.PollenPlugin&focus=1)(),
        Tests(project=true),
        Git(ssh=true),
        GitHubActions(),
        Develop(),
        ProjectFile(),
    ],
    user="lorenzoh", julia=v"1.6")
```

Copying to vscode is fine (plain text).

**Comment by lorenzoh** [comment]
Ah, I see the HTML copying is a bit too smart. I've added the feature request to https://github.com/lorenzoh/Pollen.jl/issues/29 👍
